name: build-container
on:
  push:
    tags:
      - "v*"

  workflow_dispatch:

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Get the latest tag for reference during build
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
        id: latest_tag

      - uses: actions/checkout@v2
        name: Checkout the latest tag.
        with:
          ref: "${{ steps.latest_tag.outputs.tag }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          #context:
          push: true
          # Set to same as DockerHub repository
          tags: ${GITHUB_REPOSITORY#*\/}:${{ steps.latest_tag.outputs.tag }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}